GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/70082
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation

###
GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/cfsb1739559272444
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###

GET https://fhir.cloudintersystems.com/csp/healthshare/demo/fhir/r4/Patient
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###

GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient?name=John
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###


GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient/cfsb1739559272444/_history/18
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###


GET http://127.0.0.1:8080/csp/healthshare/demo/fhir/r4/Patient?identifier=http://hospital.example.org/mrn|987654
Authorization: Basic _System:ISCDEMO
Accept: */*
content-type: application/fhir+json
Accept-Encoding: gzip, deflate, br
Prefer: return=representation
###

